### PR TITLE
Add documentation for PostgreSQL server

### PR DESCRIPTION
**Pull request by silkeh**
## Description

Add documentation for the PostgreSQL server. This contains both a (very basic) usage guide, and the upgrade instructions for 10.14 to 13.2.

### Submitter Checklist

- [x] Updated the "lastmod" portion at the top of any modified Markdown files.
- [x] Squashed commits with `git rebase -i` (if needed)

### CODE REVIEW

**Review by JoshStrobl — CHANGES_REQUESTED** [review]
1. Not sure why you are doing the references like `[1]` instead of Markdown link syntax.
2. Don't use 80 columsn
3. You aren't properly numbering everything, you're doing everything as `1.`
4. They could really just be header level 3 instead of individual list items

**Comment by silkeh** [comment]
> Not sure why you are doing the references like [1] instead of Markdown link syntax.

I assume you mean inline links, as this is Markdown link syntax? :confused:
I wrote it this way because it makes the source a bit easier to read.

> Don't use 80 columsn

:+1: 

> You aren't properly numbering everything, you're doing everything as 1.

Markdown auto-numbers, so there shouldn't really be a difference. I can change it if you insist.

> They could really just be header level 3 instead of individual list items

They could be, but I think it makes sense to have (short) instructions in an ordered/numbered list. I could also remove the numbers entirely?

**Comment by TraceyC77** [comment]
Just wanted to provide some feedback from a readability perspective. I work with professional document writers in my day job, as well as write & update test cases.

>     1. Not sure why you are doing the references like `[1]` instead of Markdown link syntax.
> 
>     2. Don't use 80 columsn

>     3. You aren't properly numbering everything, you're doing everything as `1.`
Markdown auto-numbers, as @silkeh pointed out. When auto-numbering exists, it's better to use it than not. You can see the proper number in the file preview view
https://github.com/getsolus/help-center-docs/pull/275/files?short_path=4249499#diff-42494993f88d3678d69d042806b447d73f1724274204c5626f7bb115f8a52990

>     4. They could really just be header level 3 instead of individual list items
I agree that for a set of instructions, they are more easily parsed as a numbered list. Also, when it comes to troubleshooting a problem someone might have when using these instructions, it makes it easier for them to communicate. For instance, they can say "when I followed step 4 I ran into..."

At work, we find these kinds of formatting decisions useful.

**Comment by silkeh** [comment]
@JoshStrobl I've removed the hard wraps. Please let me know if the links and numbering are really an issue, and I'll change those as well.

**Comment by JoshStrobl** [comment]
Yes, both of those are still an issue to me, so I would appreciate if they were addressed :)

**Comment by silkeh** [comment]
@JoshStrobl done!

**Comment by JoshStrobl** [comment]
Sorry for the delay. Going to get this landed and will go out with a blog post alongside all the news related to GNOME 40 upgrade, KDE bits, Qt5, etc.

**Pull request merged**
