### PR TITLE
Replace "Solus 3" with "Solus 4"

### PR DESCRIPTION
**Pull request by Justinzobel**
Changed Solus 3 to 4.

## Description

Fix outdated info

### Submitter Checklist

- [X] Updated the "lastmod" portion at the top of any modified Markdown files.
- [X] Squashed commits with `git rebase -i` (if needed)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
This isn't accurate though. We started shipping with the `linux-current` kernel in Solus 3. Maybe it would just be simpler to say:

> By default, the Solus utilizes our `linux-current` kernel.

**Comment by Justinzobel** [comment]
Solus 3 is an old release, not current, but yes, making it version agnostic
makes sense.

**Comment by Justinzobel** [comment]
Fixed.

**Comment by JoshStrobl** [comment]
Thanks!

**Pull request merged**
