### PR TITLE
Rename "Help Center Home", add Devlog

### PR DESCRIPTION
**Pull request by davidjharder**
Changes:
- index.tsx: Add a "Devlog" entry to match the navbar
- navbar and index.tsx: Rename "Help Center Home" to "Users"
- navbar: Change the leftmost entry (which points to the index) from "Solus" to "Solus Help Center"
- Rework the index grid for 3 entries

Rationale:
- "Help Center Home" is too generic, "Users" is more specific
- The actual "home" (top level page for https://help.getsol.us) is somewhere else

Bikeshedding: Suggest a better icon for "devlog" from here https://mui.com/material-ui/material-icons/?query=fe&theme=Outlined

Screenshot_20240129_184812

### CODE REVIEW

**Comment by EbonJaeger** [comment]
Looks good. I just wonder if there's a way to better indicate that the left-most item in the top navbar takes you to the index page of the help center. It doesn't really look like the other links, and the text "Solus" doesn't make me think that it'll take me to the Help Center index.

**Comment by davidjharder** [comment]
You have a point. 
Idea:
Screenshot_20240128_151451

**Comment by davidjharder** [comment]
Any opinions on this @TraceyC77 ?

**Comment by EbonJaeger** [comment]
Would having a link item called "Home" that goes to the Help Center index and just the logo itself go to https://getsol.us be too confusing? Also thinking that there's really no good way to go to the main website from the Help Center.

**Comment by davidjharder** [comment]
We could steal/borrow the "more" element from https://docs.buddiesofbudgie.org/

Also, I should rework the leftmost footer column

**Comment by davidjharder** [comment]
@EbonJaeger see new screenshot in the description.
- Rearranged the footer somewhat
- Added a dropdown to the header

The logo and the text "Solus Help Center" are part of the same element, they can't be split to point to different urls

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks! :)

**Pull request merged**
