### PR TITLE
Add checkdeps

### LINKED ISSUE #417: Packaging Docs: Update for checkdeps
getsolus/ypkg#45 deserves a change to the relevant packaging docs. CC @GZGavinZhao

### PR DESCRIPTION
**Pull request by davidjharder**
Add info about checkdeps to the following pages:

- packaging changes
- package.yml
- packaging-practices (just a stub for now)

Fixes #417

### CODE REVIEW

**Comment by davidjharder** [comment]
Hold on, table formatting is borked

**Comment by GZGavinZhao** [comment]
Thanks a lot @davidjharder! Everything looks good. I just need to give a little think on what wording I want to use for the "packaging practice" section. Would you mind if I take over/commandeer this PR from now on?

**Comment by davidjharder** [comment]
@GZGavinZhao I've committed all my work on this. Feel free to commandeer the PR.

**Comment by TraceyC77** [comment]
@GZGavinZhao - I'm changing this to Draft status since it looks like you want to add to it before it merges. If this is incorrect, my apologies.

**Comment by davidjharder** [comment]
Hey @GZGavinZhao , do you mind if I merge this?

**Comment by GZGavinZhao** [comment]
No problem, go ahead! Thanks for finishing this!

**Pull request merged**
