### PR TITLE
Updated Desktop Background section

### PR DESCRIPTION
**Pull request by johnandmegh**
## Description

Updates screenshots and instructions for changing desktop background to what I see in Budgie 10.8.2, Solus 4.5 - related to #131 

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

### CODE REVIEW

**Comment by davidjharder** [comment]
You can delete the old screenshots if they are not used anywhere else. 

An easy way to check:

- Install ripgrep `eopkg it ripgrep`
- From within the repository run `rg "budgie-background-right-click.jpg"` 
- This should spit back all the mentions of that file name within files

**Review by davidjharder — CHANGES_REQUESTED** [review]
See previous comment

**Comment by johnandmegh** [comment]
Hi - since I'm new to all of this I just wanted to check if this was correct - I ran the tool you mentioned for the three files that aren't needed on that page anymore, and they don't show up elsewhere, so I added deletions of those files to this pull request - let me know if that's OK?

Thanks! (Included the last line below just to make sure the tool was working / I had correctly cloned the repository:

```
johnkizer@boxes-solus ~/help-docs $ rg "budgie-background-section.jpg"
johnkizer@boxes-solus ~/help-docs $ rg "budgie-background-selection.jpg"
johnkizer@boxes-solus ~/help-docs $ rg "budgie-background-right-click.jpg"
johnkizer@boxes-solus ~/help-docs $ rg "budgie-desktop-blank-space-right-click.jpg"
docs/user/editions/budgie/configuration.md
234:![Budgie Desktop Right-Click Menu](configuration/budgie-desktop-blank-space-right-click.jpg)
```

**Review by johnandmegh — COMMENTED** [review]
Sorry, the [comment I left on the general request](https://github.com/getsolus/help-center-docs/pull/456#issuecomment-1893026392) probably should have gone here instead!

**Review by davidjharder — APPROVED** [review]
Looks good to me. Thanks!

Yes, you understood my intent with the `ripgrep` tool.

You don't need to have each deletion be it's own commit. You can group changes onto one commit since they're all part of the same pull request; and also I'm going to "squash" all your commits in this pull request into one larger commit anyway.

**Comment by johnandmegh** [comment]
Thanks David - I think I need to read up a *lot* more on how to work with Git/GitHub! I realize what I'm sending is really messy, thanks for the help!

**Comment by davidjharder** [comment]
No problem. It's definitely idiosyncratic, so don't worry if you find yourself scratching your head. Congrats on your first few PRs

**Pull request merged**
