### PR TITLE
package.yml: adjust formatting to Solus style

### PR DESCRIPTION
**Pull request by Staudey**
## Description

package.yml: adjust formatting to Solus style and add a `<!-- prettier-ignore -->` to exclude it from the yarn prettier

Also add the homepage key, and slightly prettify tables below

### Submitter Checklist

- [x] Updated the "date" portion at the top of any modified Markdown files.
- [x] Squashed commits with `git rebase -i` (if needed)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Did you use `yarn prettier` or do this by hand?

**Comment by Staudey** [comment]
Both ^^

Because `yarn prettier` doesn't like our custom yaml format

**Comment by JoshStrobl** [comment]
We'll want to add `docs/packaging/package.yml.md`  to `.prettierignore`, as well as any other doc where we reference our YAML format, in that case otherwise this change will continue to be overridden by prettier.

**Comment by Staudey** [comment]
Thanks for the suggestion!

I've gone a bit finer-grained and added a `<!-- prettier-ignore -->` above the yaml section to only exclude that part, and still have the prettier support for the big tables beneath.

**Comment by JoshStrobl** [comment]
Ah yea that works too :+1:

**Pull request merged**
